default:
    trainer: ppo
    batch_size: 2024
    beta: 5.0e-3
    buffer_size: 20240
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 1e6
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 3
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 3000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals: 
        extrinsic:
            strength: 1.0
            gamma: 0.995
